"""empty message

Revision ID: f97ab5cd6b1f
Revises: c98b81edfb5a
Create Date: 2022-06-18 22:08:45.289302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f97ab5cd6b1f'
down_revision = 'c98b81edfb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'all_deposit')
    op.drop_column('funds', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('funds', sa.Column('all_deposit', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
