version: '3.9'
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/stockService
    environment:
      - DB_HOST=mysql
      - DB_USER=matteovk
      - DB_PASSWORD=admin
      - DB_DATABASE=stock
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - stock_network

  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=stock
      - MYSQL_USER=matteovk
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - stock_network

networks:
  stock_network:
volumes:
  mysql:
  mysql_config: